server:
  port: 8090
spring:
  application:
    name: trade-server
  config:
    import: classpath:cred.yaml

  datasource:
    primary:
      url: jdbc:postgresql://100.115.108.27:5432/postgres
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
    secondary:
      url: jdbc:postgresql://192.168.1.53:5432/postgres
      username: user
      password: password
      driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: true
  task:
    scheduling:
      enabled: true
custom:
  logger:
    folder: logs
    level: info